def e2e_in_commit
pipeline{
    agent any
    
    options{
    // set time stamps on the log
    timestamps()
    
    // set gitlab connection where to sent an update
    gitLabConnection('my repo')
    }
    
    tools {
        maven "maven 3.6.2"
        jdk "java 8 kit"
    }
    stages{
        stage("checkout"){
            when{
                anyOf {
                    branch "realeas/*"
                }
            }
            steps{
                
                echo "========checking out (loking hella fine)========"
                deleteDir()
                checkout scm
                sh "mvn clean"
                sh "git checkout ${GIT_BRANCH}"
            }
        }
        stage("Calculate and set 3-number version"){
            when{
                anyOf {
                    branch "realeas/*"
                }
            }
            steps{
                echo "========Calculate and set 3-number version========"
                withMaven {
                    configFileProvider([configFile(fileId: '0a5edd42-4379-4509-a49e-d8ba1384edeb', variable: 'set')]) {
                        withCredentials( [usernamePassword( credentialsId: 'artyfactory', 
                                      usernameVariable: 'USERNAME', 
                                      passwordVariable: 'PASSWORD')]) {
                            script{
                                sh """
                                
                                NEXTVERSION=\$(git describe --tags | cut -d '-' -f1 | awk -F. -v OFS=. '{\$NF += 1 ; print}')
                                
                                if [ \$NEXTVERSION ] 
                                then
                                    NEXTVERSION=\$(git describe --tags | cut -d '-' -f1 | awk -F. -v OFS=. '{\$NF += 1 ; print}')
                                    echo "\${NEXTVERSION}" > v.txt
                                else
                                    NEXTVERSION="\$(git branch | grep '*'| cut -d '/' -f2).1"
                                    echo "\$(git branch | grep '*'| cut -d '/' -f2).1" > v.txt
                                fi
                                
                                nextnomatch=\$(echo \$NEXTVERSION | cut -d "." -f1,2)

                                if [ \$nextnomatch != "\$(git branch | grep '*'| cut -d '/' -f2)" ]
                                then
                                NEXTVERSION="\$(git branch | grep '*'| cut -d '/' -f2).1"
                                echo "\$(git branch | grep '*'| cut -d '/' -f2).1" > v.txt
                                fi
                                lastT=\$(curl -u ${USERNAME}:${PASSWORD} "http://172.31.39.103:8082/artifactory/libs-release-local/com/lidar/telemetry/" | grep ">\$(git branch | grep '*'| cut -d '/' -f2)" | tail -n 1 | cut -d '\"' -f 2 | cut -d '/' -f 1 )      
                                lastA=\$(curl -u ${USERNAME}:${PASSWORD} "http://172.31.39.103:8082/artifactory/libs-release-local/com/lidar/analytics/" | grep ">\$(git branch | grep '*'| cut -d '/' -f2)" | tail -n 1 | cut -d '\"' -f 2 | cut -d '/' -f 1 )      

                                
                                mvn versions:set -DnewVersion=\$NEXTVERSION
                                #mvn -s ${set}  versions:use-releases
                                mvn -s ${set} versions:set-property -Dproperty=telemetry.version -DnewVersion="\$lastT"
                                mvn -s ${set} versions:set-property -Dproperty=analytics.version -DnewVersion="\$lastA"
                                mvn dependency:list
                                """            
                            }
                        }
                    }
                }
            }
            post{
                always{
                    echo "========Calculate and set 3-number version finished========"

                }
                success{
                    echo "========Calculate and set 3-number version executed successfully========"
                }
                failure{
                    echo "========Calculate and set 3-number version execution failed========"
                }
            }
        }
        stage("build"){
            when{
                anyOf {
                    branch "realeas/*"
                }
            }
            steps{
                echo "========executing build========"
                
                withMaven {
                    configFileProvider([configFile(fileId: '0a5edd42-4379-4509-a49e-d8ba1384edeb', variable: 'set')]) {
                        sh "mvn -s ${set} package"
                    } 
                } // withMaven will discover the generated Maven artifacts, JUnit Surefire & FailSafe reports and FindBugs reports
                
            }
            post{
                success{
                    echo "========build executed successfully========"
                }
                failure{
                    echo "========build execution failed========"
                }
            }
        }
        stage("e2e tests"){
            when{
                anyOf {
                    branch "realeas/*"
                }
            }
            steps{
                echo "========executing tests========"
                script{
                     withCredentials( [usernamePassword( credentialsId: 'artyfactory', 
                                      usernameVariable: 'USERNAME', 
                                      passwordVariable: 'PASSWORD')]) {
                        // build project
                       sh """
                       wget http://172.31.39.103:8082/artifactory/libs-snapshot-local/com/lidar/simulator/99-SNAPSHOT/simulator-99-20230110.103625-1.jar --user=${USERNAME} --password=${PASSWORD}
                       ls
                       unzip target/leader-product-\$(cat v.txt)-leader-lidar.zip
                       ls | grep telemetry
                       java -cp \$(ls | grep telemetry):\$(ls | grep analytics):simulator-99-20230110.103625-1.jar com.lidar.simulation.Simulator
                       """
                    }
                }
            }
            post{
                always{
                    echo "========tests are done========"
                }
                success{
                    echo "========tests executed successfully========"
                }
                failure{
                    echo "========tests execution failed========"
                }
            }
        }
        stage("publish "){
            when{
                anyOf {
                    branch "realeas/*"
                }
            }
            steps{
                echo "========executing publishing to artifactory========"
                withMaven {
                    configFileProvider([configFile(fileId: '0a5edd42-4379-4509-a49e-d8ba1384edeb', variable: 'set')]) {
                        sh "mvn -s ${set} deploy -DskipTests"
                    } 
                } 
            }
            post{
                success{
                    echo "========publish executed successfully========"
                }
                failure{
                    echo "========publish execution failed========"
                }
            }
        }
         stage("push tag"){
            when{
                anyOf {
                    branch "realeas/*"
                }
            }
            steps{
                echo "========executing pushing tag========"
                script{
                    sh "git tag \$(cat v.txt)"
                    //sh "git remote set-url origin git@gitlab:gitlab-instance-24b2f4ed/suggest-lib.git"
                    sh "git push origin \$(cat v.txt)"
                }
            }
            post{
                success{
                    echo "========tags push executed successfully========"
                }
                failure{
                    echo "========tags push execution failed========"
                }
            }
        }
    }
    post{
        always{
            echo "========pipline done========"
        }
         success{
            echo "========pipeline executed successfully ========"
            
            // updating the git status to the git reposetory 
            updateGitlabCommitStatus name: "all good", state: "success" 
        }
        failure{
            echo "========pipeline execution failed========"
            
            // updating the git status to the git reposetory 
            updateGitlabCommitStatus name: "error", state: "failed" 
        }
    }
}

